package Net::Async::Spotify::Object::Album;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Album);


=head1 NAME
 
Net::Async::Spotify::Object::Album - Package representing Main Spotify Album Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Album
Will hold all extra functionality for Spotify Album Object

=head1 METHODS

=cut


1;
