package Net::Async::Spotify::Object::AudioFeatures;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::AudioFeatures);


=head1 NAME
 
Net::Async::Spotify::Object::AudioFeatures - Package representing Main Spotify AudioFeatures Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::AudioFeatures
Will hold all extra functionality for Spotify AudioFeatures Object

=head1 METHODS

=cut


1;
