package Net::Async::Spotify::Object::Category;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Category);


=head1 NAME
 
Net::Async::Spotify::Object::Category - Package representing Main Spotify Category Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Category
Will hold all extra functionality for Spotify Category Object

=head1 METHODS

=cut


1;
