package Net::Async::Spotify::Object::Context;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Context);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::Context - Package representing Main Spotify Context Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Context
Will hold all extra functionality for Spotify Context Object

=head1 METHODS

=cut

1;
