package Net::Async::Spotify::Object::CurrentlyPlayingContext;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::CurrentlyPlayingContext);


=head1 NAME
 
Net::Async::Spotify::Object::CurrentlyPlayingContext - Package representing Main Spotify CurrentlyPlayingContext Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::CurrentlyPlayingContext
Will hold all extra functionality for Spotify CurrentlyPlayingContext Object

=head1 METHODS

=cut


1;
