package Net::Async::Spotify::Object::CurrentlyPlaying;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::CurrentlyPlaying);


=head1 NAME
 
Net::Async::Spotify::Object::CurrentlyPlaying - Package representing Main Spotify CurrentlyPlaying Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::CurrentlyPlaying
Will hold all extra functionality for Spotify CurrentlyPlaying Object

=head1 METHODS

=cut


1;
