package Net::Async::Spotify::Object::Cursor;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Cursor);


=head1 NAME
 
Net::Async::Spotify::Object::Cursor - Package representing Main Spotify Cursor Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Cursor
Will hold all extra functionality for Spotify Cursor Object

=head1 METHODS

=cut


1;
