package Net::Async::Spotify::Object::CursorPaging;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::CursorPaging);


=head1 NAME
 
Net::Async::Spotify::Object::CursorPaging - Package representing Main Spotify CursorPaging Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::CursorPaging
Will hold all extra functionality for Spotify CursorPaging Object

=head1 METHODS

=cut


1;
