package Net::Async::Spotify::Object::Devices;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Devices);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::Devices - Package representing Main Spotify Devices Object

=head1 DESCRIPTION

Main module for an Autogenerated one L<Net::Async::Spotify::Object::Generated::Devices>.
Will hold all extra functionality for Spotify Devices Object

=head1 METHODS

=cut

1;
