package Net::Async::Spotify::Object::Device;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Device);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::Device - Package representing Main Spotify Device Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Device
Will hold all extra functionality for Spotify Device Object

=head1 METHODS

=cut

1;
