package Net::Async::Spotify::Object::Disallows;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Disallows);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::Disallows - Package representing Main Spotify Disallows Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Disallows
Will hold all extra functionality for Spotify Disallows Object

=head1 METHODS

=cut

1;
