package Net::Async::Spotify::Object::Episode;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Episode);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::Episode - Package representing Main Spotify Episode Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Episode
Will hold all extra functionality for Spotify Episode Object

=head1 METHODS

=cut

1;
