package Net::Async::Spotify::Object::Error;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Error);


=head1 NAME
 
Net::Async::Spotify::Object::Error - Package representing Main Spotify Error Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Error
Will hold all extra functionality for Spotify Error Object

=head1 METHODS

=cut


1;
