package Net::Async::Spotify::Object::ExternalId;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::ExternalId);


=head1 NAME
 
Net::Async::Spotify::Object::ExternalId - Package representing Main Spotify ExternalId Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::ExternalId
Will hold all extra functionality for Spotify ExternalId Object

=head1 METHODS

=cut


1;
