package Net::Async::Spotify::Object::Followers;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Followers);


=head1 NAME
 
Net::Async::Spotify::Object::Followers - Package representing Main Spotify Followers Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Followers
Will hold all extra functionality for Spotify Followers Object

=head1 METHODS

=cut


1;
