package Net::Async::Spotify::Object::Image;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Image);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::Image - Package representing Main Spotify Image Object

=head1 DESCRIPTION

Main module for an Autogenerated one L<Net::Async::Spotify::Object::Generated::Image>.
Will hold all extra functionality for Spotify Image Object

=head1 METHODS

=cut

1;
