package Net::Async::Spotify::Object::Image;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Image);


=head1 NAME
 
Net::Async::Spotify::Object::Image - Package representing Main Spotify Image Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Image
Will hold all extra functionality for Spotify Image Object

=head1 METHODS

=cut


1;
