package Net::Async::Spotify::Object::LinkedTrack;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::LinkedTrack);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::LinkedTrack - Package representing Main Spotify LinkedTrack Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::LinkedTrack
Will hold all extra functionality for Spotify LinkedTrack Object

=head1 METHODS

=cut

1;
