package Net::Async::Spotify::Object::Paging;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Paging);


=head1 NAME
 
Net::Async::Spotify::Object::Paging - Package representing Main Spotify Paging Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Paging
Will hold all extra functionality for Spotify Paging Object

=head1 METHODS

=cut


1;
