package Net::Async::Spotify::Object::PlaylistTracksRef;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::PlaylistTracksRef);


=head1 NAME
 
Net::Async::Spotify::Object::PlaylistTracksRef - Package representing Main Spotify PlaylistTracksRef Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::PlaylistTracksRef
Will hold all extra functionality for Spotify PlaylistTracksRef Object

=head1 METHODS

=cut


1;
