package Net::Async::Spotify::Object::PlaylistTracksRef;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::PlaylistTracksRef);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::PlaylistTracksRef - Package representing Main Spotify PlaylistTracksRef Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::PlaylistTracksRef
Will hold all extra functionality for Spotify PlaylistTracksRef Object

=head1 METHODS

=cut

1;
