package Net::Async::Spotify::Object::PlayerError;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::PlayerError);


=head1 NAME
 
Net::Async::Spotify::Object::PlayerError - Package representing Main Spotify PlayerError Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::PlayerError
Will hold all extra functionality for Spotify PlayerError Object

=head1 METHODS

=cut


1;
