package Net::Async::Spotify::Object::PlayHistory;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::PlayHistory);


=head1 NAME
 
Net::Async::Spotify::Object::PlayHistory - Package representing Main Spotify PlayHistory Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::PlayHistory
Will hold all extra functionality for Spotify PlayHistory Object

=head1 METHODS

=cut


1;
