package Net::Async::Spotify::Object::PrivateUser;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::PrivateUser);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::PrivateUser - Package representing Main Spotify PrivateUser Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::PrivateUser
Will hold all extra functionality for Spotify PrivateUser Object

=head1 METHODS

=cut

1;
