package Net::Async::Spotify::Object::PublicUser;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::PublicUser);


=head1 NAME
 
Net::Async::Spotify::Object::PublicUser - Package representing Main Spotify PublicUser Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::PublicUser
Will hold all extra functionality for Spotify PublicUser Object

=head1 METHODS

=cut


1;
