package Net::Async::Spotify::Object::RecommendationSeed;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::RecommendationSeed);


=head1 NAME
 
Net::Async::Spotify::Object::RecommendationSeed - Package representing Main Spotify RecommendationSeed Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::RecommendationSeed
Will hold all extra functionality for Spotify RecommendationSeed Object

=head1 METHODS

=cut


1;
