package Net::Async::Spotify::Object::ResumePoint;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::ResumePoint);


=head1 NAME
 
Net::Async::Spotify::Object::ResumePoint - Package representing Main Spotify ResumePoint Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::ResumePoint
Will hold all extra functionality for Spotify ResumePoint Object

=head1 METHODS

=cut


1;
