package Net::Async::Spotify::Object::SavedShow;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SavedShow);


=head1 NAME
 
Net::Async::Spotify::Object::SavedShow - Package representing Main Spotify SavedShow Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SavedShow
Will hold all extra functionality for Spotify SavedShow Object

=head1 METHODS

=cut


1;
