package Net::Async::Spotify::Object::SavedAlbum;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SavedAlbum);


=head1 NAME
 
Net::Async::Spotify::Object::SavedAlbum - Package representing Main Spotify SavedAlbum Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SavedAlbum
Will hold all extra functionality for Spotify SavedAlbum Object

=head1 METHODS

=cut


1;
