package Net::Async::Spotify::Object::SavedTrack;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SavedTrack);


=head1 NAME
 
Net::Async::Spotify::Object::SavedTrack - Package representing Main Spotify SavedTrack Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SavedTrack
Will hold all extra functionality for Spotify SavedTrack Object

=head1 METHODS

=cut


1;
