package Net::Async::Spotify::Object::SavedEpisode;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SavedEpisode);


=head1 NAME
 
Net::Async::Spotify::Object::SavedEpisode - Package representing Main Spotify SavedEpisode Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SavedEpisode
Will hold all extra functionality for Spotify SavedEpisode Object

=head1 METHODS

=cut


1;
