package Net::Async::Spotify::Object::SimplifiedAlbum;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SimplifiedAlbum);


=head1 NAME
 
Net::Async::Spotify::Object::SimplifiedAlbum - Package representing Main Spotify SimplifiedAlbum Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SimplifiedAlbum
Will hold all extra functionality for Spotify SimplifiedAlbum Object

=head1 METHODS

=cut


1;
