package Net::Async::Spotify::Object::SimplifiedArtist;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SimplifiedArtist);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::SimplifiedArtist - Package representing Main Spotify SimplifiedArtist Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SimplifiedArtist
Will hold all extra functionality for Spotify SimplifiedArtist Object

=head1 METHODS

=cut

1;
