package Net::Async::Spotify::Object::SimplifiedEpisode;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SimplifiedEpisode);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::SimplifiedEpisode - Package representing Main Spotify SimplifiedEpisode Object

=head1 DESCRIPTION

Main module for an Autogenerated one L<Net::Async::Spotify::Object::Generated::SimplifiedEpisode>.
Will hold all extra functionality for Spotify SimplifiedEpisode Object

=head1 METHODS

=cut

1;
