package Net::Async::Spotify::Object::SimplifiedTrack;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SimplifiedTrack);


=head1 NAME
 
Net::Async::Spotify::Object::SimplifiedTrack - Package representing Main Spotify SimplifiedTrack Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SimplifiedTrack
Will hold all extra functionality for Spotify SimplifiedTrack Object

=head1 METHODS

=cut


1;
