package Net::Async::Spotify::Object::SimplifiedEpisode;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SimplifiedEpisode);


=head1 NAME
 
Net::Async::Spotify::Object::SimplifiedEpisode - Package representing Main Spotify SimplifiedEpisode Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SimplifiedEpisode
Will hold all extra functionality for Spotify SimplifiedEpisode Object

=head1 METHODS

=cut


1;
