package Net::Async::Spotify::Object::SimplifiedShow;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SimplifiedShow);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::SimplifiedShow - Package representing Main Spotify SimplifiedShow Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SimplifiedShow
Will hold all extra functionality for Spotify SimplifiedShow Object

=head1 METHODS

=cut

1;
