package Net::Async::Spotify::Object::SimplifiedPlaylist;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::SimplifiedPlaylist);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::SimplifiedPlaylist - Package representing Main Spotify SimplifiedPlaylist Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::SimplifiedPlaylist
Will hold all extra functionality for Spotify SimplifiedPlaylist Object

=head1 METHODS

=cut

1;
