package Net::Async::Spotify::Object::TrackRestriction;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::TrackRestriction);


=head1 NAME
 
Net::Async::Spotify::Object::TrackRestriction - Package representing Main Spotify TrackRestriction Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::TrackRestriction
Will hold all extra functionality for Spotify TrackRestriction Object

=head1 METHODS

=cut


1;
