package Net::Async::Spotify::Object::Track;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::Track);


=head1 NAME
 
Net::Async::Spotify::Object::Track - Package representing Main Spotify Track Object
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::Track
Will hold all extra functionality for Spotify Track Object

=head1 METHODS

=cut


1;
