package Net::Async::Spotify::Object::TuneableTrack;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::Object::Generated::TuneableTrack);

=encoding utf8

=head1 NAME

Net::Async::Spotify::Object::TuneableTrack - Package representing Main Spotify TuneableTrack Object

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::Object::Generated::TuneableTrack
Will hold all extra functionality for Spotify TuneableTrack Object

=head1 METHODS

=cut

1;
