package Net::Async::Spotify::API::Albums;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Albums);

=head1 NAME
 
Net::Async::Spotify::API::Albums - Package representing Main Spotify Albums API
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Albums.
Will hold all extra functionality for Spotify Albums API 
 
=head1 METHODS

=cut

1;
