package Net::Async::Spotify::API::Artists;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Artists);

=encoding utf8

=head1 NAME

Net::Async::Spotify::API::Artists - Package representing Main Spotify Artists API

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Artists.
Will hold all extra functionality for Spotify Artists API

=head1 METHODS

=cut

1;
