package Net::Async::Spotify::API::Base;

use strict;
use warnings;

use Future::AsyncAwait;

=head1 NAME

Net::Async::Spotify::API::Base - Base Package for Spotify API Classes.

=head1 DESCRIPTION

Base class to be used by all Autogenerated modules of Spotify API

=head1 METHODS

=cut

sub new {
    my $self = bless { @_[1..$#_] }, $_[0];
    die "no ->spotify provided" unless $self->spotify;
    $self;
}

sub spotify { shift->{spotify} }


=head2 call_api

Calls Spotify API with the passed params.

=cut

async sub call_api {
    my ($self, $request, $response_objs, %args) = @_;
}

1;
