package Net::Async::Spotify::API::Episodes;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Episodes);

=encoding utf8

=head1 NAME

Net::Async::Spotify::API::Episodes - Package representing Main Spotify Episodes API

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Episodes.
Will hold all extra functionality for Spotify Episodes API

=head1 METHODS

=cut

1;
