package Net::Async::Spotify::API::Follow;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Follow);

=head1 NAME
 
Net::Async::Spotify::API::Follow - Package representing Main Spotify Follow API
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Follow.
Will hold all extra functionality for Spotify Follow API 
 
=head1 METHODS

=cut

1;
