package Net::Async::Spotify::API::Library;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Library);

=encoding utf8

=head1 NAME

Net::Async::Spotify::API::Library - Package representing Main Spotify Library API

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Library.
Will hold all extra functionality for Spotify Library API

=head1 METHODS

=cut

1;
