package Net::Async::Spotify::API::Personalization;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Personalization);

=encoding utf8

=head1 NAME

Net::Async::Spotify::API::Personalization - Package representing Main Spotify Personalization API

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Personalization.
Will hold all extra functionality for Spotify Personalization API

=head1 METHODS

=cut

1;
