package Net::Async::Spotify::API::Player;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Player);

=encoding utf8

=head1 NAME

Net::Async::Spotify::API::Player - Package representing Main Spotify Player API

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Player.
Will hold all extra functionality for Spotify Player API

=head1 METHODS

=cut

1;
