package Net::Async::Spotify::API::Search;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Search);

=encoding utf8

=head1 NAME

Net::Async::Spotify::API::Search - Package representing Main Spotify Search API

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Search.
Will hold all extra functionality for Spotify Search API

=head1 METHODS

=cut

1;
