package Net::Async::Spotify::API::Shows;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Shows);

=head1 NAME
 
Net::Async::Spotify::API::Shows - Package representing Main Spotify Shows API
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Shows.
Will hold all extra functionality for Spotify Shows API 
 
=head1 METHODS

=cut

1;
