package Net::Async::Spotify::API::Tracks;

use strict;
use warnings;

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Tracks);

=head1 NAME
 
Net::Async::Spotify::API::Tracks - Package representing Main Spotify Tracks API
 
=head1 DESCRIPTION
 
Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Tracks.
Will hold all extra functionality for Spotify Tracks API 
 
=head1 METHODS

=cut

1;
