package Net::Async::Spotify::API::Users;

use strict;
use warnings;

# VERSION
# AUTHORITY

use mro;
use parent qw(Net::Async::Spotify::API::Generated::Users);

=encoding utf8

=head1 NAME

Net::Async::Spotify::API::Users - Package representing Main Spotify Users API

=head1 DESCRIPTION

Main module for an Autogenerated one Net::Async::Spotify::API::Generated::Users.
Will hold all extra functionality for Spotify Users API

=head1 METHODS

=cut

1;
